### ISSUE TITLE
slow when maximizing/restoring windows

### ISSUE THREAD

**Issue by VPraharsha03** [doncsugar/sumac-theme#1]
i've observed a slight lag or slutter when using Summaculate dark for window decoration while maximizing/restoring/tiling the windows -- I've tried changing the window decoration to other themes and didn't notice such lag. I've kvantum theme also enabled --

**Comment by doncsugar** [comment]
Do you also experience this lag with Summaculate Dark Opaque? How about Summaculate Light Blur?

Can you link the window decorations you are using that do not have this problem? The performance difference may come from having blur enabled on the decoration. If this is the case, unfortunately the only fix it is to report the bug to KDE.

**Comment by VPraharsha03** [comment]
I see this only when I try to maximize/restore window by dragging to the top corner of the screen

**Comment by VPraharsha03** [comment]
@doncsugar Is there a Summaculate theme for GTK applications ?

**Comment by VPraharsha03** [comment]
> Do you also experience this lag with Summaculate Dark Opaque? How about Summaculate Light Blur?
> 
> Can you link the window decorations you are using that do not have this problem? The performance difference may come from having blur enabled on the decoration. If this is the case, unfortunately the only fix it is to report the bug to KDE.

@doncsugar The difference between dark blur & dark opaque is very slight or none.. same I've found with light variants too with both of the decorations, whenever I try to maximize the window by dragging it's titlebar to the top the transition is choppy and not smooth, I've tried disabling every animation but no improvement 

the only window decoration themes where I don't notice this lag is with breeze or plastik

**Comment by doncsugar** [comment]
> @doncsugar Is there a Summaculate theme for GTK applications ?

There is not, but I recommend vinceliuice's WhiteSur. You can see my recommendations here: https://store.kde.org/p/2130847

> the only window decoration themes where I don't notice this lag is with breeze or plastik

When you said that you tried other themes, did you mean that you only tried it with Breeze and Plastik? Breeze and Plastik are very different from Aurorae themes in that they do not use svg assets to draw themselves.

Do you experience this choppiness with other window decorations downloaded from the store? If Summaculate is the only theme exhibiting this behavior, please list themes that do not have this choppiness.

**Comment by VPraharsha03** [comment]
> When you said that you tried other themes, did you mean that you only tried it with Breeze and Plastik? Breeze and Plastik are very different from Aurorae themes in that they do not use svg assets to draw themselves.

Other two themes that use SVG assets I've tried are Edna & Utterly Round Dark -- and I could see the same problem.

> Do you experience this choppiness with other window decorations downloaded from the store? If Summaculate is the only theme exhibiting this behavior, please list themes that do not have this choppiness.

Edna & Utterly Round Dark have the same choppiness, I might try more themes to see. But I think this isn't particular to summaculate @doncsugar

**Comment by VPraharsha03** [comment]
Few users have reported about the same issue with aurorae window decorations [here](https://www.reddit.com/r/kde/comments/1b7rm5t/issue_with_aurorae_window_decorations/) as well as [here](https://www.reddit.com/r/kde/comments/u1imjd/using_different_window_decorations_causes_lag_is/)

**Comment by doncsugar** [comment]
Thanks for the confirmation that this is a bug with Aurorae. If you would like this bug to be fixed, you can make an account and file a report to KDE here: https://bugs.kde.org

**Comment by VPraharsha03** [comment]
to anyone who's interested the main bug ticket is open [here](https://bugs.kde.org/show_bug.cgi?id=431643)
